### ISSUE TITLE
Choose Wordpress theme

### ISSUE THREAD

**Issue by pomatoV** [WaalbrugWire/portfolio#3]
Suggestions needed for a theme for a portfolio website.

**Comment by pomatoV** [comment]
- https://www.vwthemes.net/vw-portfolio-pro/
- Portfolio Lite: https://organicthemes.com/demo/?demo=portfolio-lite
- WP Portfolio: https://www.themehorse.com/preview/wp-portfolio
- Seos Portfolio: http://portfolio.local/wp-admin/theme-install.php?theme=seos-portfolio

**Comment by pomatoV** [comment]
Please vote on a theme.

**Comment by pomatoV** [comment]
I vote for Seos Theme.

**Comment by hooneytunes** [comment]
I vote for WP Portfolio

**Comment by StefanJansen23** [comment]
I vote for organicthemes

**Comment by GTSep** [comment]
I vote for Portfolio Lite

**Comment by pomatoV** [comment]
Votes so far:
- 2X Portfolio Lite from Organic Themes
- 1X WP Portfolio
- 1X Seos Portfolio

Due to majority votes, I suggest we pick Portfolio Lite theme. Any objections?

**Comment by hooneytunes** [comment]
No

**Comment by GTSep** [comment]
Nope
